name: Format Check

on:
  pull_request:
    branches: [ main ]

jobs:
  check-formatting:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format

      - name: Restore dependencies
        working-directory: ./FinTrack
        run: dotnet restore FinTrack.sln

      - name: Check formatting
        working-directory: ./FinTrack
        run: dotnet format FinTrack.sln --no-restore --verify-no-changes